# Generated by Django 5.1.2 on 2024-10-17 11:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merchant_balance'),
        ('transaction', '0004_alter_transaction_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approver',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='approved_transactions', to='home.bankstaff'),
        ),
    ]
