# Generated by Django 5.1.2 on 2024-10-18 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0005_alter_transaction_approver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='approver',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
