# Generated by Django 5.1.2 on 2024-10-27 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('transaction', '0007_transaction_merchant_account'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='merchant_account',
        ),
    ]
