# Generated by Django 5.1.2 on 2024-10-11 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='merchant',
            name='balance',
        ),
    ]
