# Generated by Django 5.1.2 on 2024-10-11 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_remove_merchant_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='merchant',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10),
        ),
    ]
