# Generated by Django 5.1.2 on 2024-10-27 20:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_merchant_balance'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OtpModel',
        ),
    ]
