# Generated by Django 5.1.2 on 2024-10-27 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_delete_otpmodel'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankstaff',
            name='merchant_account',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.merchant'),
        ),
    ]
