# Generated by Django 5.1.2 on 2024-11-01 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_accesslog_delete_otpmodel'),
        ('home', '0005_bankstaff_merchant_account'),
    ]

    operations = [
    ]
