# Generated by Django 5.1.2 on 2024-11-02 12:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_merge_20241102_0222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankstaff',
            name='merchant_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='home.merchant'),
        ),
    ]
