# mysite_nginx.conf

# configuration of the server
server {
    # the port your site will be served on
    listen 80;
    # the domain name it will serve for
    server name 4205-24s1-2-1-i, 172.25.77.25, 4205-24s1-2-3-i, 172.25.77.42; # substitute your machine's IP address or FQDN
    charset utf-8;

    # max upload size
    client_max body _ size 75M;     # adjust to taste

    # Django media
    location /media {
        alias /path/to/your/mysite/media; # your Django project's media files - amend as req
    }

    location /static {
        alias C:/Users/e0969036/MerchantVault/static;     # your Django project's static files - amend as req, make sure to change
                                                             # under nginx/available-sites and nginx/sites-enabled as well
    }

    # Finally, send all non-media requests to the Django server.
    location / {
    proxy_pass http://localhost:8080; # See output from runserver.py
    }
}